fgs_gestion_comptes_home:
    path:     /
    defaults: { _controller: FGSGestionComptesBundle:Aide:first }
fgs_gestion_comptes_admin:
    path:     /Admin
    defaults: { _controller: FGSGestionComptesBundle:Aide:admin }

fgs_gestion_comptes_all:
    path:     /connect
    defaults: { _controller: FGSGestionComptesBundle:Aide:home }
    methods:  [GET]


fgs_gestion_comptes_homepage:
    path:     /vos-comptes
    defaults: { _controller: FGSGestionComptesBundle:Comptes:index }
    methods:  [GET]
    
fgs_gestion_comptes_ajouter_compte: 
    path:     /ajouter-compte
    defaults: { _controller: FGSGestionComptesBundle:Comptes:ajouterCompte }
    methods:  [GET, POST]
    
    
fgs_gestion_comptes_gerer_compte: 
    path:     /gerer-compte
    defaults: { _controller: FGSGestionComptesBundle:Comptes:gererCompte }
    methods:  [GET]
    
fgs_gestion_comptes_supprimer_compte: 
    path:     /supprimer-compte
    defaults: { _controller: FGSGestionComptesBundle:Comptes:supprimerCompte }
    methods:  [POST]

fgs_gestion_comptes_modifier_compte: 
    path:     /modifier-compte/{id}
    defaults: { _controller: FGSGestionComptesBundle:Comptes:modifierCompte }
    requirements:
        id:    \d+
    methods:  [GET, POST]
        
fgs_gestion_comptes_gerer_categories:
    path:     /gerer-categories-compte
    defaults: { _controller: FGSGestionComptesBundle:Categories:gererCategories }
    methods:  [GET]
    
fgs_gestion_comptes_ajouter_categorie:
    path:     /ajouter-categorie
    defaults: { _controller: FGSGestionComptesBundle:Categories:ajouterCategorie }
    methods:  [GET, POST]
    
fgs_gestion_comptes_modifier_categorie:
    path:     /modifier-categorie/{id}
    defaults: { _controller: FGSGestionComptesBundle:Categories:modifierCategorie }
    requirements:
        id:    \d+
    methods:  [GET, POST]
        
fgs_gestion_comptes_supprimer_categorie:
    path:     /supprimer-categorie
    defaults: { _controller: FGSGestionComptesBundle:Categories:supprimerCategorie }
    methods:  [POST]
        
fgs_gestion_comptes_monter_categorie:
    path:     /monter-categorie/{id}
    defaults: { _controller: FGSGestionComptesBundle:Categories:monterCategorie }
    requirements:
        id:    \d+
    methods:  [GET]
        
fgs_gestion_comptes_descendre_categorie:
    path:     /descendre-categorie/{id}
    defaults: { _controller: FGSGestionComptesBundle:Categories:descendreCategorie }
    requirements:
        id:    \d+
    methods:  [GET]
        
fgs_gestion_comptes_ajouter_depense:
    path:     /ajouter-depense
    defaults: { _controller: FGSGestionComptesBundle:Mouvements:ajouterDepense }
    methods:  [GET, POST]
    
fgs_gestion_comptes_ajouter_revenu:
    path:     /ajouter-revenu
    defaults: { _controller: FGSGestionComptesBundle:Mouvements:ajouterRevenu }
    methods:  [GET, POST]
    
fgs_gestion_comptes_supprimer_mouvement_financier:
    path:     /supprimer-mouvement-financier
    defaults: { _controller: FGSGestionComptesBundle:Mouvements:supprimerMouvementFinancier }
    methods:  [POST]
        
fgs_gestion_comptes_modifier_mouvement_financier:
    path:     /modifier-mouvement-financier/{id}
    defaults: { _controller: FGSGestionComptesBundle:Mouvements:modifierMouvementFinancier }
    requirements:
        id:    \d+
    methods:  [GET, POST]
         
fgs_gestion_comptes_check_mouvement_financier:
    path:     /check-mouvement-financier
    defaults: { _controller: FGSGestionComptesBundle:Mouvements:checkMouvementFinancier }
    methods:  [POST]
              
fgs_gestion_comptes_visualiser_mouvement_financier_compte:
    path:     /visualiser-mouvement-financiers-compte/{id}/{debut}/{longueur}
    defaults: { _controller: FGSGestionComptesBundle:Mouvements:voirMouvementFinancierCompte, debut:0, longueur:30 }
    requirements:
        id:       \d+
        debut:    \d+
    methods:  [GET]

fgs_gestion_comptes_visualiser_mouvement_financier_compte_mois:
    path:     /visualiser-mouvement-financiers-compte-mois/{id}/{annee}/{mois}
    defaults: { _controller: FGSGestionComptesBundle:Mouvements:voirMouvementFinancierCompteMois, annee:null, mois:null }    
    requirements:
        id:       \d+
        annee:    \d{4}
        mois:     \d+
    methods:  [GET]

fgs_gestion_comptes_visualiser_mouvement_financier_compte_annee:
    path:     /visualiser-mouvement-financiers-compte-annee/{id}/{annee}
    defaults: { _controller: FGSGestionComptesBundle:Mouvements:voirMouvementFinancierCompteAnnee, annee:null }    
    requirements:
        id:       \d+
        annee:    \d{4}
    methods:  [GET]

fgs_gestion_comptes_ajouter_depense_planifiee:
    path:     /planifier-depense
    defaults: { _controller: FGSGestionComptesBundle:MouvementsPlanifies:ajouterDepensePLanifiee }
    methods:  [GET, POST]
        
fgs_gestion_comptes_ajouter_revenu_planifie:
    path:     /planifier-revenu
    defaults: { _controller: FGSGestionComptesBundle:MouvementsPlanifies:ajouterRevenuPLanifie }
    methods:  [GET, POST]
    
fgs_gestion_comptes_voir_mouvements_planifies:
    path:     /visualiser-mouvements-planifies
    defaults: { _controller: FGSGestionComptesBundle:MouvementsPlanifies:voirMouvementFinancierPlanifie }
    methods:  [GET]

fgs_gestion_comptes_modifier_mouvements_planifies:
    path:     /modifier-mouvement-financier-planifie/{id}
    defaults: { _controller: FGSGestionComptesBundle:MouvementsPlanifies:modifierMouvementFinancierPlanifie }
    requirements:
        id:    \d+  
    methods:  [GET, POST]
   
fgs_gestion_comptes_supprimer_mouvement_financier_planifie:
    path:     /supprimer-mouvement-financier-planifie
    defaults: { _controller: FGSGestionComptesBundle:MouvementsPlanifies:supprimerMouvementFinancierPlanifie }
    methods:  [POST]
        
fgs_gestion_comptes_test_mail:
    path:     /test-mail
    defaults: { _controller: FGSGestionComptesBundle:Mail:testMail }
    methods:  [GET]

fgs_gestion_comptes_welcome:
    path:     /bienvenue
    defaults: { _controller: FGSGestionComptesBundle:Aide:bienvenue }
    methods:  [GET]

fgs_gestion_comptes_ajouter_virement:
    path:     /ajouter-virement
    defaults: { _controller: FGSGestionComptesBundle:Virement:ajouterVirement }
    methods:  [GET, POST]


fgs_gestion_comptes_ajouter_reclamation:
    path:     /ajouter-reclamation
    defaults: { _controller: FGSGestionComptesBundle:Reclamation:AjoutReclamation }
    methods:  [GET, POST]

fgs_gestion_comptes_afficherC_reclamation:
    path:     /afficherC-reclamation
    defaults: { _controller: FGSGestionComptesBundle:Reclamation:LireReclamations2 }
    methods:  [GET, POST]

lire_reclamations:
    path:     /lireReclamations
    defaults: { _controller: FGSGestionComptesBundle:Reclamation:LireReclamations }


etat:
    path:     /etat/{id}
    defaults: { _controller: FGSGestionComptesBundle:Reclamation:Etat }


fgs_gestion_comptes_ajouterBanque:
    path:     /admin/ajouterBanque
    defaults: { _controller: FGSGestionComptesBundle:Banque:ajouterBanque }
fgs_gestion_comptes_afficherBanques:
    path:     /admin/afficherBanque
    defaults: { _controller: FGSGestionComptesBundle:Banque:afficherBanque }
fgs_gestion_comptes_afficher_Utilisateurs:
    path:     /admin/afficherUsers
    defaults: { _controller: FGSGestionComptesBundle:User:afficherAll }
fgs_gestion_comptes_banir_Utilisateurs:
    path:     /admin/banirUsers/{id}
    defaults: { _controller: FGSGestionComptesBundle:User:Etat }
fgs_gestion_comptes_Unbanir_Utilisateurs:
    path:     /admin/UnbanirUsers/{id}
    defaults: { _controller: FGSGestionComptesBundle:User:Etat2 }