imports:
    - { resource: "@FGSUserBundle/Resources/config/security.yml" }

security:
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/test-mail, role: ROLE_SUPER_ADMIN}
        - { path: ^/Admin/, role: ROLE_ADMIN }
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                #csrf_token_generator: security.csrf.token_manager
                default_target_path:  fgs_gestion_comptes_all
                failure_path: fgs_gestion_comptes_home
            logout:       true
            anonymous:    true
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
