<?php

namespace Proxies\__CG__\FGS\GestionComptesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CategorieMouvementFinancier extends \FGS\GestionComptesBundle\Entity\CategorieMouvementFinancier implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'FGS\\GestionComptesBundle\\Entity\\CategorieMouvementFinancier' . "\0" . 'id', '' . "\0" . 'FGS\\GestionComptesBundle\\Entity\\CategorieMouvementFinancier' . "\0" . 'libelle', '' . "\0" . 'FGS\\GestionComptesBundle\\Entity\\CategorieMouvementFinancier' . "\0" . 'icone', '' . "\0" . 'FGS\\GestionComptesBundle\\Entity\\CategorieMouvementFinancier' . "\0" . 'ordre', '' . "\0" . 'FGS\\GestionComptesBundle\\Entity\\CategorieMouvementFinancier' . "\0" . 'parent', '' . "\0" . 'FGS\\GestionComptesBundle\\Entity\\CategorieMouvementFinancier' . "\0" . 'childrens', '' . "\0" . 'FGS\\GestionComptesBundle\\Entity\\CategorieMouvementFinancier' . "\0" . 'type', '' . "\0" . 'FGS\\GestionComptesBundle\\Entity\\CategorieMouvementFinancier' . "\0" . 'utilisateur', 'level'];
        }

        return ['__isInitialized__', '' . "\0" . 'FGS\\GestionComptesBundle\\Entity\\CategorieMouvementFinancier' . "\0" . 'id', '' . "\0" . 'FGS\\GestionComptesBundle\\Entity\\CategorieMouvementFinancier' . "\0" . 'libelle', '' . "\0" . 'FGS\\GestionComptesBundle\\Entity\\CategorieMouvementFinancier' . "\0" . 'icone', '' . "\0" . 'FGS\\GestionComptesBundle\\Entity\\CategorieMouvementFinancier' . "\0" . 'ordre', '' . "\0" . 'FGS\\GestionComptesBundle\\Entity\\CategorieMouvementFinancier' . "\0" . 'parent', '' . "\0" . 'FGS\\GestionComptesBundle\\Entity\\CategorieMouvementFinancier' . "\0" . 'childrens', '' . "\0" . 'FGS\\GestionComptesBundle\\Entity\\CategorieMouvementFinancier' . "\0" . 'type', '' . "\0" . 'FGS\\GestionComptesBundle\\Entity\\CategorieMouvementFinancier' . "\0" . 'utilisateur', 'level'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CategorieMouvementFinancier $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __contruct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__contruct', []);

        return parent::__contruct();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelle($libelle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelle', [$libelle]);

        return parent::setLibelle($libelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelle', []);

        return parent::getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setIcone($icone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIcone', [$icone]);

        return parent::setIcone($icone);
    }

    /**
     * {@inheritDoc}
     */
    public function getIcone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIcone', []);

        return parent::getIcone();
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', []);

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(\FGS\GestionComptesBundle\Entity\CategorieMouvementFinancier $parent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', [$parent]);

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function hasParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasParent', []);

        return parent::hasParent();
    }

    /**
     * {@inheritDoc}
     */
    public function getChildrens()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChildrens', []);

        return parent::getChildrens();
    }

    /**
     * {@inheritDoc}
     */
    public function setChildrens(\Doctrine\Common\Collections\ArrayCollection $childrens)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChildrens', [$childrens]);

        return parent::setChildrens($childrens);
    }

    /**
     * {@inheritDoc}
     */
    public function addChildren(\FGS\GestionComptesBundle\Entity\CategorieMouvementFinancier $children)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChildren', [$children]);

        return parent::addChildren($children);
    }

    /**
     * {@inheritDoc}
     */
    public function hasChildren()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasChildren', []);

        return parent::hasChildren();
    }

    /**
     * {@inheritDoc}
     */
    public function getLevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLevel', []);

        return parent::getLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setLevel($level)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLevel', [$level]);

        return parent::setLevel($level);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdre', []);

        return parent::getOrdre();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrdre($ordre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrdre', [$ordre]);

        return parent::setOrdre($ordre);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilisateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilisateur', []);

        return parent::getUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilisateur($utilisateur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilisateur', [$utilisateur]);

        return parent::setUtilisateur($utilisateur);
    }

}
